name: 'athlete_dashboard'
version: '1.0.0'
config-version: 2

profile: 'dbt'

# Define all your source directories
model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

# These directories will be cleaned when you run `dbt clean`
clean-targets:
  - 'target'
  - 'dbt_packages'


# Project-wide configurations
models:
  athlete_dashboard:
    
    # Default (if not overridden)
    +materialized: view
    +schema: 'strava_data'
    
    staging:
      +materialized: view
      +schema: 'strava_staging'
      +tags: ['staging', 'strava']

    intermediate:
      +materialized: view
      +schema: 'strava_intermediate'
      +tags: ['intermediate', 'strava']

    marts:
      +materialized: table
      +schema: 'strava_marts'
      +tags: ['mart', 'strava']

# Project-level variables
vars:
  dim_date_start: '2024-10-12'
  dim_date_end: '2030-12-31'
