version: 2

models:
  - name: stg_activities
    columns:
      # Core identifiers
      - name: activity_id
        description: "Unique identifier for each activity."
        tests:
          - not_null
          - unique

      - name: athlete_id
        description: "Unique identifier of the athlete who performed the activity."
        tests:
          - not_null

      - name: map_id
        description: "Identifier for the Strava map object linked to this activity."

      # Basic info
      - name: name
        description: "Activity name as entered in Strava (e.g., 'Morning Ride')."
        tests:
          - not_null

      - name: type
        description: "Deprecated Strava activity type field (legacy)."

      - name: sport_type
        description: "Current Strava activity sport type (e.g., 'Run', 'Ride', 'Swim')."
        tests:
          - not_null
          # - accepted_values:
          #   arguments:
          #     values: ['Ride', 'Run', 'Swim', 'Hike', 'Walk', 'VirtualRide', 'WeightTraining', 'InlineSkate']

      - name: distance_m
        description: "Distance covered in meters."


      - name: moving_time_s
        description: "Time spent moving, in seconds."
      - name: elapsed_time_s
        description: "Total elapsed time including pauses, in seconds."
      - name: elevation_gain_m
        description: "Total elevation gain in meters."

      # Timestamps
      - name: start_date_utc
        description: "Start time in UTC."
        tests:
          - not_null

      - name: start_date_local
        description: "Start time in the athlete's local timezone."
      - name: timezone
        description: "Timezone string (e.g. 'Europe/Vienna')."

      # Location
      - name: location_city
        description: "City of activity (if available)."
      - name: location_state
        description: "State or region of activity."
      - name: location_country
        description: "Country where the activity occurred."

      # Performance
      - name: avg_speed_mps
        description: "Average speed in meters per second."
      - name: max_speed_mps
        description: "Maximum speed in meters per second."
      - name: avg_heartrate
        description: "Average heart rate (bpm)."
      - name: max_heartrate
        description: "Maximum heart rate (bpm)."
      - name: avg_cadence
        description: "Average cadence (rpm)."
      - name: avg_temp_c
        description: "Average temperature (°C)."
      - name: energy_kj
        description: "Energy output in kilojoules."
      - name: avg_watts
        description: "Average power output in watts."
      - name: max_watts
        description: "Maximum power output in watts."
      - name: weighted_watts
        description: "Weighted average power over the activity."

      # Meta flags
      - name: is_trainer
        description: "TRUE if performed on a trainer (indoor)."
      - name: is_commute
        description: "TRUE if marked as commute."
      - name: is_manual
        description: "TRUE if manually entered activity."
      - name: is_private
        description: "TRUE if private activity."
      - name: is_flagged
        description: "TRUE if flagged on Strava."
      - name: has_heartrate
        description: "TRUE if heart rate data available."
      - name: visibility
        description: "Visibility setting of the activity."

      # Engagement
      - name: achievement_count
        description: "Number of achievements earned."
      - name: kudos_count
        description: "Number of kudos received."
      - name: comment_count
        description: "Number of comments."
      - name: photo_count
        description: "Number of photos uploaded."

      # Map info
      - name: map_polyline
        description: "Encoded map polyline for the route."
      - name: map_resource_state
        description: "Strava map resource state integer."

      # Upload / Metadata
      - name: upload_id
        description: "Upload identifier for this activity."
      - name: upload_id_str
        description: "Upload identifier as string."
      - name: external_id
        description: "External reference (e.g., from device file)."
      - name: resource_state
        description: "Resource state flag from Strava API."
      - name: _staged_at
        description: "Timestamp when data was staged by dbt."

  - name: stg_athlete_info
    description: >
      Cleaned and typed staging model for Strava athlete information.

    columns:
      - name: athlete_id
        description: "Unique identifier for the athlete."
        tests:
          - not_null
          - unique

      - name: username
        description: "The athlete's Strava username (may be null if user hides it)."
      - name: first_name
        description: "The athlete's first name."
      - name: last_name
        description: "The athlete's last name."
      - name: bio
        description: "Short biography or about section from the athlete's Strava profile."
      - name: city
        description: "City the athlete is located in."
      - name: state
        description: "State or region of the athlete."
      - name: country
        description: "Country of the athlete."
      - name: sex
        description: "The athlete's gender as provided by Strava (e.g., 'M', 'F', or null)."
        tests:
          - accepted_values:
              values: ['M', 'F']

      - name: has_premium
        description: "Boolean flag indicating if the athlete has a Strava Premium account."
      - name: has_summit
        description: "Boolean flag indicating if the athlete has a Summit membership."

      - name: badge_type_id
        description: "Strava badge type identifier for visual rank or level (nullable)."
      - name: weight_kg
        description: "Weight of the athlete in kilograms."
      - name: profile_medium
        description: "URL to the athlete's medium-sized profile image."
      - name: profile
        description: "URL to the athlete's full-size profile image."
      - name: friend
        description: "Friend relationship status relative to the authenticated user."
      - name: follower
        description: "Follower relationship status relative to the authenticated user."

      - name: created_at
        description: "Timestamp when the athlete account was created on Strava."
        tests:
          - not_null
      - name: updated_at
        description: "Timestamp when the athlete record was last updated."
        tests:
          - not_null

      - name: resource_state
        description: "Resource state returned by Strava indicating object completeness (1=meta, 2=summary, 3=detailed)."
      - name: _staged_at
        description: "Timestamp when this record was staged (dbt load timestamp)."

  - name: stg_athlete_stats
    description: >
      Cleaned and typed staging model for Strava athlete statistics.
    
    columns:
      - name: athlete_id
        description: "Unique identifier for the athlete."
        tests:
          - not_null
          - unique

      - name: biggest_ride_distance_m
        description: "Longest single ride distance in meters."

      - name: biggest_climb_elevation_m
        description: "Greatest single climb elevation gain in meters."

      - name: recent_ride_totals_distance_m
        description: "Total distance of rides in the recent period (meters)."

      - name: recent_ride_totals_moving_time_s
        description: "Total moving time of rides in the recent period (seconds)."

      - name: recent_ride_totals_elevation_gain_m
        description: "Total elevation gain of rides in the recent period (meters)."

      - name: recent_run_totals_distance_m
        description: "Total distance of runs in the recent period (meters)."

      - name: recent_run_totals_moving_time_s
        description: "Total moving time of runs in the recent period (seconds)."

      - name: recent_run_totals_elevation_gain_m
        description: "Total elevation gain of runs in the recent period (meters)."

      - name: recent_swim_totals_distance_m
        description: "Total distance of swims in the recent period (meters)."

      - name: recent_swim_totals_moving_time_s
        description: "Total moving time of swims in the recent period (seconds)."

      - name: recent_swim_totals_elevation_gain_m
        description: "Total elevation gain of swims in the recent period (meters)."

      - name: all_ride_totals_distance_m
        description: "All-time total distance of rides (meters)."

      - name: all_ride_totals_moving_time_s
        description: "All-time total moving time of rides (seconds)."

      - name: all_ride_totals_elevation_gain_m
        description: "All-time total elevation gain of rides (meters)."

      - name: all_run_totals_distance_m
        description: "All-time total distance of runs (meters)."

      - name: all_run_totals_moving_time_s
        description: "All-time total moving time of runs (seconds)."

      - name: all_run_totals_elevation_gain_m
        description: "All-time total elevation gain of runs (meters)."
