version: 2

models:
  # Activities
  - name: stg_activities
    description: "Staging model for Strava activities. One row = one Strava activity. Casts types, normalizes units, and adds basic derived metrics and time breakdowns."
    columns:

      # Core identifiers
      - name: activity_id
        description: "Unique identifier for each activity in Strava."
        tests:
          - not_null
          - unique

      - name: athlete_id
        description: "Unique identifier of the athlete who performed the activity."
        tests:
          - not_null

      - name: map_id
        description: "Identifier of the map object associated with this activity in Strava. Used to look up polylines and map metadata."

      - name: gear_id
        description: "Identifier of the gear (bike, shoes) used for this activity."

      # Basic info
      - name: activity_name
        description: "Activity title as recorded in Strava (e.g. 'Morning Ride')."
        tests:
          - not_null

      - name: sport_type
        description: "Canonical Strava sport type (Run, Ride, Swim, VirtualRide, etc.)."
        tests:
          - not_null
          # - accepted_values:
          #     values: ['Ride', 'Run', 'Swim', 'Hike', 'Walk', 'VirtualRide', 'WeightTraining', 'InlineSkate']

      - name: workout_type
        description: "Workout sub-type / interval type (Strava field, sometimes null)."

      - name: distance_m
        description: "Distance covered in meters."

      - name: moving_time_s
        description: "Active moving time in seconds (excludes pauses)."

      - name: elapsed_time_s
        description: "Total elapsed time in seconds (includes pauses)."

      - name: elevation_gain_m
        description: "Total elevation gain in meters."

      # Timestamps
      - name: start_date_utc
        description: "Activity start time in UTC, as reported by Strava."
        tests:
          - not_null

      - name: start_date_local
        description: "Activity start time localized to the athlete's timezone."
        tests:
          - not_null

      - name: timezone
        description: "IANA timezone label for the activity (e.g. 'Europe/Vienna')."

      - name: utc_offset_s
        description: "UTC offset of the activity's local time, in seconds."

      # Time breakdowns (derived)
      - name: activity_date_local
        description: "Local calendar date (YYYY-MM-DD) of the activity start."

      - name: activity_year
        description: "Local activity start year (e.g. 2025)."

      - name: activity_month
        description: "Local activity start month number (1-12)."

      - name: activity_weekday
        description: "Day of week of the start time (1=Sunday in BigQuery, 2=Monday, ... 7=Saturday)."

      - name: activity_hour_local
        description: "Hour of day (0-23) when the activity started, in local time."

      # Location
      - name: location_city
        description: "City of the activity, if provided by Strava."
      - name: location_state
        description: "Region / state of the activity, if provided."
      - name: location_country
        description: "Country of the activity."

      # Engagement / social
      - name: achievement_count
        description: "Number of segment achievements earned in this activity."
      - name: kudos_count
        description: "Number of kudos received from other athletes."
      - name: comment_count
        description: "Number of comments left on this activity."
      - name: athlete_count
        description: "Number of athletes in the activity (e.g. group ride)."
      - name: photo_count
        description: "Number of photos associated with this activity."

      # Boolean flags
      - name: is_trainer
        description: "TRUE if the activity was performed on a trainer (indoor ride / treadmill)."
      - name: is_commute
        description: "TRUE if the activity is marked as a commute."
      - name: is_manual
        description: "TRUE if this activity was manually entered (not recorded via device)."
      - name: is_flagged
        description: "TRUE if the activity is flagged in Strava."
      - name: has_heartrate
        description: "TRUE if heart rate data is present for this activity."
      - name: visibility
        description: "Visibility setting for this activity (e.g. 'everyone', 'followers_only', etc.)."

      # Performance (core telemetry)
      - name: avg_speed_mps
        description: "Average moving speed in meters per second (distance/moving_time as understood by Strava)."

      - name: max_speed_mps
        description: "Maximum speed in meters per second."

      - name: avg_heartrate
        description: "Average heart rate in beats per minute."
      - name: max_heartrate
        description: "Maximum heart rate in beats per minute."

      - name: avg_cadence
        description: "Average cadence (typically RPM for cycling, or steps/min for running depending on sport)."

      - name: avg_temp_c
        description: "Average temperature in Celsius for the activity."
      - name: energy_kj
        description: "Total reported work in kilojoules."
      - name: avg_watts
        description: "Average power in watts."
      - name: max_watts
        description: "Maximum instantaneous power in watts."
      - name: weighted_watts
        description: "Weighted average power (Strava's 'weighted_average_watts')."

      - name: elev_high_m
        description: "Highest elevation reached during the activity, in meters."
      - name: elev_low_m
        description: "Lowest elevation reached during the activity, in meters."

      # Derived performance metrics
      - name: avg_pace_min_per_km
        description: "Average pace in minutes per kilometer, computed as (moving_time / distance). Lower is faster."

      - name: avg_speed_kph
        description: "Average moving speed in kilometers per hour (converted from avg_speed_mps)."

      - name: max_speed_kph
        description: "Maximum speed in kilometers per hour (converted from max_speed_mps)."

      - name: avg_speed_overall_kph
        description: "Overall door-to-door speed in km/h, computed as distance / elapsed_time (includes pauses)."

      - name: idle_time_s
        description: "Seconds not moving = elapsed_time_s - moving_time_s. Higher often means lots of stopping (traffic lights, coffee, photos)."

      # Map info
      - name: map_polyline
        description: "Encoded polyline of the route for mapping / visualization."

      # Upload / lineage
      - name: upload_id
        description: "Upload identifier from Strava for this activity."
      - name: upload_id_str
        description: "Upload identifier as string (Strava sometimes provides both int and string forms)."
      - name: external_id
        description: "External source identifier (e.g. original FIT/GPX filename or device ID)."

  # Activity Streams
  - name: stg_activity_streams
    description: >
      Staging model for Strava activity streams. Each row represents a single data point in an activity's telemetry stream.
    
    columns:
      - name: activity_id
        description: 'Identifier of the activity this stream data point belongs to.'
        tests:
          - not_null

      - name: stream_type
        description: 'Type of the stream data (e.g., time, distance, altitude, heartrate, cadence, watts, etc.).'
        tests:
          - not_null
  
  # Athlete Profile
  - name: stg_athlete_info
    description: >
      Cleaned and typed staging model for Strava athlete profile information.
      Contains personal, geographic, and account-related attributes for a single athlete,
      as returned by the Strava API.

    config:
      contract:
        enforced: false

    columns:
      # Identifiers
      - name: athlete_id
        description: "Unique identifier for the athlete."
        data_type: INT64
        tests:
          - not_null
          - unique

      - name: firstname
        description: "Athlete's first name."
        data_type: STRING

      - name: lastname
        description: "Athlete's last name."
        data_type: STRING

  # Athlete Statistics
  - name: stg_athlete_stats
    description: >
      Cleaned and typed staging model for Strava athlete statistics.
      Contains lifetime, recent, and year-to-date aggregated metrics
      for a single athlete, as returned by the Strava API.
    
    config:
      contract:
        enforced: false

    columns:
      # Identifiers & metadata
      - name: athlete_id
        description: "Unique identifier for the athlete."
        data_type: INT64
        tests:
          - not_null
          - unique

      - name: fetched_at
        description: "Timestamp when the statistics snapshot was fetched from the Strava API."
        data_type: TIMESTAMP

      - name: _staged_at
        description: "Timestamp when this record was staged in dbt."
        data_type: TIMESTAMP

      # Other columns are defined in stg_athlete_stats.sql
      # as they are numerous and derived.

  # Gear Details
  - name: stg_gear_details
    description: >
      Staging model for Strava gear details.
      One row per gear_id, representing the most recent known state of each gear item.
      Raw append-only records are deduplicated by selecting the latest ingested record.

    config:
      contract:
        enforced: true
    
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - gear_id

    columns:
      # Identifiers
      - name: gear_id
        description: "Unique identifier for the gear item in Strava."
        data_type: STRING
        tests:
          - not_null
          - unique

      # Naming & classification
      - name: name
        description: "Name of the gear as provided by Strava."
        data_type: STRING
      - name: nickname
        description: "User-defined nickname for the gear."
        data_type: STRING
      - name: brand_name
        description: "Manufacturer brand of the gear."
        data_type: STRING
      - name: model_name
        description: "Model name of the gear."
        data_type: STRING
      - name: frame_type
        description: >
          Numeric code indicating frame type (Strava enum).
          Typically distinguishes road, mountain, gravel, etc.
        data_type: INT64

      # Status flags
      - name: is_primary
        description: "TRUE if this gear is marked as the athlete's primary gear."
        data_type: BOOL
        tests:
          - not_null
      - name: is_retired
        description: "TRUE if the gear has been retired by the athlete."
        data_type: BOOL
        tests:
          - not_null

      # Usage & distance
      - name: distance_m
        description: "Total accumulated distance for this gear in meters."
        data_type: INT64
        tests:
          - dbt_utils.expression_is_true:
              column_name: distance_m
              expression: ">= 0"

      - name: distance_km
        description: "Total accumulated distance for this gear in kilometers."
        data_type: FLOAT64
        tests:
          - dbt_utils.expression_is_true:
              column_name: distance_km
              expression: ">= 0"

      - name: notification_distance_km
        description: >
          Distance threshold in kilometers at which Strava sends maintenance notifications.
        data_type: FLOAT64
      
      # Physical properties
      - name: weight_kg
        description: "Weight of the gear in kilograms, if provided."
        data_type: FLOAT64

      # Metadata
      - name: description
        description: "Free-text description of the gear."
        data_type: STRING

      - name: ingested_at
        description: >
          UTC timestamp when this record was ingested.
          Used for deduplication to select the latest record per gear_id.
        data_type: TIMESTAMP
        tests:
          - not_null:
              severity: warn
