version: 2


models:
  # Activities
  - name: stg_activities
    description: "Staging model for Strava activities. One row = one Strava activity. Casts types, normalizes units, and adds basic derived metrics and time breakdowns."
    
    config:
      meta:
        domain: strava
        grain: "One row per Strava activity."
        source_systems:
          - source: strava_data
            table: raw_activities
      contract:
        enforced: false
    
    columns:
      # Core identifiers
      - name: activity_id
        description: "Unique identifier for each activity in Strava."
        data_type: INT64
        tests:
          - not_null
          - unique

      - name: athlete_id
        description: "Unique identifier of the athlete who performed the activity." 
        data_type: INT64
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_athlete_info')
                field: athlete_id
              config:
                severity: warn

      - name: map_id
        description: "Identifier of the map object associated with this activity in Strava. Used to look up polylines and map metadata."
        data_type: STRING

      - name: gear_id
        description: "Identifier of the gear (bike, shoes) used for this activity."
        data_type: STRING
        tests:
          - relationships:
              arguments:
                to: ref('stg_gear_details')
                field: gear_id
              config:
                severity: warn

      # Basic info
      - name: activity_name
        description: "Activity title as recorded in Strava (e.g. 'Morning Ride')."
        data_type: STRING
        tests:
          - not_null

      - name: sport_type
        description: "Canonical Strava sport type (Run, Ride, Swim, etc.)."
        data_type: STRING
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Ride','Run','Swim','Hike','Walk','VirtualRide', 'WeightTraining', 'InlineSkate']
              config:
                severity: warn

      # Timestamps
      - name: start_date_utc
        description: "Activity start time in UTC, as reported by Strava."
        data_type: TIMESTAMP
        tests:
          - not_null

      - name: start_date_local
        description: "Activity start time localized to the athlete's timezone."
        data_type: TIMESTAMP
        tests:
          - not_null

      # Upload / lineage
      - name: upload_id
        description: "Upload identifier from Strava for this activity."
        data_type: INT64

      - name: upload_id_str
        description: "Upload identifier as string (Strava sometimes provides both int and string forms)."
        data_type: STRING
        
      - name: external_id
        description: "External source identifier (e.g. original FIT/GPX filename or device ID)."
        data_type: STRING

      - name: ingested_at
        description: "Timestamp when this activity record was ingested from the Strava API."
        data_type: TIMESTAMP

      - name: processed_at
        description: "Timestamp when this record was staged in dbt."
        data_type: TIMESTAMP

  # Activity Streams
  - name: stg_activity_streams
    description: >
      Staging model for Strava activity streams. One row per (activity_id, stream_type, sequence_index),
      representing the latest ingested telemetry point for that position in the stream.  

    config:
      meta:
        domain: strava
        grain: "One row per (activity_id, stream_type, sequence_index)."
        source_systems:
          - source: strava_data
            table: raw_activity_streams
      contract:
        enforced: true

    columns:
      - name: stream_pk
        description: >
          Surrogate primary key for a telemetry point, derived from (activity_id, stream_type, sequence_index).
        data_type: STRING
        tests:
          - not_null
          - unique

      - name: activity_id
        description: "Identifier of the activity this stream data point belongs to."
        data_type: INT64
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_activities')
                field: activity_id
              config:
                severity: warn

      - name: stream_type
        description: >
          Type of stream data (e.g. time, distance, altitude, heartrate, cadence, watts, latlng, etc.).
        data_type: STRING
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['time','distance','latlng','altitude','velocity_smooth','heartrate','cadence','watts','temp','moving','grade_smooth']
              config:
                severity: warn

      - name: sequence_index
        description: "Zero-based or ordinal index of this sample within the stream."
        data_type: INT64
        tests:
          - not_null

      - name: value_float
        description: "Numeric stream value when the payload is floating point (e.g., altitude)."
        data_type: FLOAT64

      - name: value_int
        description: "Numeric stream value when the payload is integer (e.g., heartrate, cadence)."
        data_type: INT64

      - name: value_bool
        description: "Boolean stream value when the payload is boolean."
        data_type: BOOL

      - name: value_lat
        description: "Latitude component for coordinate streams (if applicable)."
        data_type: FLOAT64

      - name: value_lng
        description: "Longitude component for coordinate streams (if applicable)."
        data_type: FLOAT64

      - name: ingested_at
        description: >
          UTC timestamp when this telemetry point was ingested. Used to deduplicate and keep the latest record.
        data_type: TIMESTAMP

      - name: processed_at
        description: "Timestamp when this record was staged in dbt."
        data_type: TIMESTAMP
  
  # Athlete Profile
  - name: stg_athlete_info
    description: >
      Cleaned and typed staging model for Strava athlete profile information.
      Contains personal, geographic, and account-related attributes for a single athlete,
      as returned by the Strava API.

    config:
      meta:
        domain: strava
        grain: "One row per athlete."
        source_systems:
          - source: strava_data
            table: raw_athlete_info
      contract:
        enforced: false

    columns:
      # Identifiers
      - name: athlete_id
        description: "Unique identifier for the athlete."
        data_type: INT64
        tests:
          - not_null
          - unique

      - name: firstname
        description: "Athlete's first name."
        data_type: STRING

      - name: lastname
        description: "Athlete's last name."
        data_type: STRING

      - name: ingested_at
        description: "Timestamp when the athlete profile was ingested from the Strava API."
        data_type: TIMESTAMP

      - name: processed_at
        description: "Timestamp when this record was staged in dbt."
        data_type: TIMESTAMP

  # Athlete Statistics
  - name: stg_athlete_stats
    description: >
      Cleaned and typed staging model for Strava athlete statistics.
      Contains lifetime, recent, and year-to-date aggregated metrics
      for a single athlete, as returned by the Strava API.
    
    config:
      meta: 
        domain: strava
        grain: "One row per athlete."
        source_systems:
          - source: strava_data
            table: raw_athlete_stats
      contract:
        enforced: false

    columns:
      # Identifiers & metadata
      - name: athlete_id
        description: "Unique identifier for the athlete."
        data_type: INT64
        tests:
          - not_null

      - name: ingested_at
        description: "Timestamp when the statistics snapshot was fetched from the Strava API."
        data_type: TIMESTAMP

      - name: processed_at
        description: "Timestamp when this record was staged in dbt."
        data_type: TIMESTAMP

  # Gear Details
  - name: stg_gear_details
    description: >
      Staging model for Strava gear details.
      One row per gear_id, representing the most recent known state of each gear item.
      Raw append-only records are deduplicated by selecting the latest ingested record.

    config:
      meta:
        domain: strava
        grain: "One row per gear item."
        source_systems:
          - source: strava_data
            table: raw_gear_details
      contract:
        enforced: false
        
    columns:
      # Identifiers
      - name: gear_id
        description: "Unique identifier for the gear item in Strava."
        data_type: STRING
        tests:
          - not_null
          - unique

      # Status flags
      - name: is_primary
        description: "TRUE if this gear is marked as the athlete's primary gear."
        data_type: BOOL
        tests:
          - not_null

      - name: is_retired
        description: "TRUE if the gear has been retired by the athlete."
        data_type: BOOL
        tests:
          - not_null

      # Usage & distance
      - name: distance_m
        description: "Total accumulated distance for this gear in meters."
        data_type: INT64
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                column_name: distance_m
                expression: ">= 0"

      - name: distance_km
        description: "Total accumulated distance for this gear in kilometers."
        data_type: FLOAT64
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                column_name: distance_km
                expression: ">= 0"

      - name: ingested_at
        description: "Timestamp when this gear record was ingested from the Strava API."
        data_type: TIMESTAMP

      - name: processed_at
        description: "Timestamp when this record was staged in dbt."
        data_type: TIMESTAMP
