name: dbt run & test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dbt (BigQuery)
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery==1.10.*  # adapter version shown in your logs

      - name: Configure dbt profile
        env:
          GCP_KEYFILE_JSON: ${{ secrets.GCP_KEYFILE_JSON }}
        run: |
          echo "$GCP_KEYFILE_JSON" > keyfile.json
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << 'YAML'
          dbt_athlete_dashboard:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: service-account
                project: athlete-dashboard-467718
                dataset: strava_data
                keyfile: keyfile.json
                location: europe-west1
                threads: 4
          YAML

      - name: Run dbt deps (if using packages)
        run: dbt deps --project-dir ./dbt_athlete_dashboard/

      - name: Build models
        run: dbt run --profiles-dir ~/.dbt --project-dir ./dbt_athlete_dashboard

      - name: Run tests
        run: dbt test --profiles-dir ~/.dbt --project-dir ./dbt_athlete_dashboard
